language: android

jdk: oraclejdk8

sudo: required

dependencies:
  pre:
    - mkdir -p ${ANDROID_HOME}/licenses
    - echo $ANDROID_SDK_LICENSE > ${ANDROID_HOME}/licenses/android-sdk-license
    - bash ./misc/download_keystore.sh
  override:
    - ./gradlew dependencies || true

test:
  override:
    - ./gradlew clean assemble -Dpre-dex=false --console=plain --stacktrace
    - ./gradlew test --console=plain
    - ./gradlew lint --console=plain

    - cp -r app/build/outputs $CIRCLE_ARTIFACTS
    - cp -r app/build/test-results/* $CIRCLE_TEST_REPORTS

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  - ".+"

script:
  ./gradlew dependencies